from typing import Dict, Any, List

EUDR_ESTATES: List[Dict[str, str]] = [
    {"id": "1021", "name": "Adipati Estate",         "spec": "EUDR"},
    {"id": "1020", "name": "Padang Halaban Estate",   "spec": "EUDR"},
    {"id": "1022", "name": "Pernantian Estate",       "spec": "EUDR"},
    {"id": "1220", "name": "Kanopan Ulu Estate",      "spec": "EUDR"},
    {"id": "2520", "name": "Sungai Buaya Estate",     "spec": "EUDR"},
    {"id": "2521", "name": "Sungai Merah Estate",     "spec": "EUDR"},
    {"id": "1920", "name": "Libo Estate",             "spec": "EUDR"},
    {"id": "1921", "name": "Kandistasari Estate",     "spec": "EUDR"},
    {"id": "1922", "name": "Nenggala Estate",         "spec": "EUDR"},
    {"id": "1923", "name": "Palapa Estate",           "spec": "EUDR"},
    {"id": "1924", "name": "Samsam Estate",           "spec": "EUDR"},
    {"id": "1925", "name": "Sungai Rokan Estate",     "spec": "EUDR"},
    {"id": "1926", "name": "Ujung Tanjung Estate",    "spec": "EUDR"},
    {"id": "2020", "name": "Naga Mas Estate",         "spec": "EUDR"},
    {"id": "2021", "name": "Naga Sakti Estate",       "spec": "EUDR"},
    {"id": "2022", "name": "Kijang Estate",           "spec": "EUDR"},
    {"id": "2121", "name": "Rama Bhakti Estate",      "spec": "EUDR"},
    {"id": "2320", "name": "Indrasakti Estate",       "spec": "EUDR"},
    {"id": "1422", "name": "Hanau Estate",            "spec": "EUDR"},
    {"id": "1423", "name": "Tanjung Paring Estate",   "spec": "EUDR"},
    {"id": "1424", "name": "Tasik Mas Estate",        "spec": "EUDR"},
    {"id": "1425", "name": "Medang Sari Estate",      "spec": "EUDR"},
    {"id": "1432", "name": "Langadang Estate",        "spec": "EUDR"},
    {"id": "3226", "name": "Perdana Estate",          "spec": "EUDR"},
    {"id": "3227", "name": "Semandau Estate",         "spec": "EUDR"},
    {"id": "3228", "name": "Muara Dua Estate",        "spec": "EUDR"},
    {"id": "3229", "name": "Lenggana Estate",         "spec": "EUDR"},
    {"id": "3820", "name": "Sulin Estate",            "spec": "EUDR"},
    {"id": "3821", "name": "Katayang Estate",         "spec": "EUDR"},
    {"id": "3822", "name": "Nahiyang Estate",         "spec": "EUDR"},
]

EUDR_MILLS: List[Dict[str, str]] = [
    {"id": "1050",         "name": "Padang Halaban Mill",   "spec": "EUDR"},
    {"id": "1451",         "name": "Hanau Mill",            "spec": "EUDR"},
    {"id": "1456",         "name": "Semilar Mill",          "spec": "EUDR"},
    {"id": "1950",         "name": "Libo Mill",             "spec": "EUDR"},
    {"id": "1951",         "name": "Samsam Mill",           "spec": "EUDR"},
    {"id": "2050",         "name": "Naga Sakti Mill",       "spec": "EUDR"},
    {"id": "2350",         "name": "Indrasakti Mill",       "spec": "EUDR"},
    {"id": "2550",         "name": "Sungai Buaya Mill",     "spec": "EUDR"},
    {"id": "2551",         "name": "Sungai Merah Mill",     "spec": "EUDR"},
    {"id": "3251",         "name": "Perdana Mill",          "spec": "EUDR"},
    {"id": "3253",         "name": "Sungai Rungau Mill",    "spec": "EUDR"},
    {"id": "3850",         "name": "Tangar Mill",           "spec": "EUDR"},
    {"id": "4250",         "name": "Jalemo Mill",           "spec": "EUDR"},
    {"id": "4450",         "name": "Kuayan Mill",           "spec": "EUDR"},
    {"id": "5150",         "name": "Sako Mill",             "spec": "EUDR"},
    {"id": "PO1000000099", "name": "Perlabian Mill",        "spec": "EUDR"},
    {"id": "PO1000001670", "name": "Umbul Mas Wisesa Mill", "spec": "EUDR"},
    {"id": "PO1000000095", "name": "Bukit Maradja Mill",    "spec": "EUDR"},
]

REFINERIES: List[Dict[str, str]] = [
    {"id": "R113",  "name": "Lubuk Gaung Refinery", "group": "Lubuk Gaung Refinery"},
    {"id": "T114",  "name": "Lampung Refinery",     "group": "Lampung Refinery"},
    {"id": "RJKT",  "name": "Marunda Refinery",     "group": "Marunda Refinery"},
    {"id": "T115",  "name": "Belawan Refinery",     "group": "Belawan Refinery"},
    {"id": "T130",  "name": "Tarjun Refinery",      "group": "Tarjun Refinery"},
    {"id": "T126",  "name": "Surabaya Refinery",    "group": "Surabaya Refinery"},
]

PRODUCTS: Dict[str, Dict[str, Any]] = {
    "CPO":    {"input": "FFB",   "oer": 0.20, "ref_yield": 1.00, "label": "Crude Palm Oil"},
    "RBDPO":  {"input": "CPO",   "oer": 1.00, "ref_yield": 0.94, "label": "RBD Palm Olein"},
    "RBDOLN": {"input": "RBDPO", "oer": 1.00, "ref_yield": 0.77, "label": "RBD Palm Olein (Low IV)"},
    "PKO":    {"input": "PK",    "oer": 0.45, "ref_yield": 1.00, "label": "Palm Kernel Oil"},
    "RBDPKO": {"input": "PKO",   "oer": 1.00, "ref_yield": 0.95, "label": "RBD Palm Kernel Oil"},
    "PFAD":   {"input": "RBDPO", "oer": 1.00, "ref_yield": 0.05, "label": "Palm Fatty Acid Distillate"},
}

MT_TANKERS: List[str] = [
    "MT Merbau", "MT Belawan Star", "MT Sriwijaya", "MT Nusantara Pride",
    "MT Kalimantan", "MT Sumatera Express", "MT Tarjun Jaya", "MT Lubuk Mas",
    "MT Lampung Bay", "MT Marunda Spirit", "MT Java Sea", "MT Mahakam",
]

LOADING_PORTS: Dict[str, str] = {
    "Lubuk Gaung Refinery": "Dumai, Riau",
    "Lampung Refinery":     "Panjang, Lampung",
    "Marunda Refinery":     "Marunda, Jakarta",
    "Belawan Refinery":     "Belawan, Medan",
    "Tarjun Refinery":      "Tarjun, Kalimantan",
    "Surabaya Refinery":    "Tanjung Perak, Surabaya",
}

BUYER_CATALOGUE: List[Dict[str, Any]] = [
    {
        "id": "BUYER_NESTE", "name": "Neste Oil",
        "country": "Finland", "segment": "Renewable Fuels / SAF",
        "max_pcf_limit": 2.5, "discharge_port": "Rotterdam, Netherlands",
        "products": {
            "CPO":    {"label":"Crude Palm Oil",         "historical_quantity_mt": 75000.0,
                       "historical_route": {"estate":{"id":"1925","name":"Sungai Rokan Estate","spec":"EUDR"},
                                            "mill":  {"id":"1950","name":"Libo Mill","spec":"EUDR"},
                                            "refinery":{"id":"R113","name":"Lubuk Gaung Refinery","group":"Lubuk Gaung Refinery"}},
                       "historical_pcf_per_unit": 1.82},
            "RBDPO":  {"label":"RBD Palm Olein",         "historical_quantity_mt": 75000.0,
                       "historical_route": {"estate":{"id":"1921","name":"Kandistasari Estate","spec":"EUDR"},
                                            "mill":  {"id":"1951","name":"Samsam Mill","spec":"EUDR"},
                                            "refinery":{"id":"T114","name":"Lampung Refinery","group":"Lampung Refinery"}},
                       "historical_pcf_per_unit": 2.11},
            "RBDOLN": {"label":"RBD Palm Olein (Low IV)","historical_quantity_mt": 75000.0,
                       "historical_route": {"estate":{"id":"1922","name":"Nenggala Estate","spec":"EUDR"},
                                            "mill":  {"id":"1950","name":"Libo Mill","spec":"EUDR"},
                                            "refinery":{"id":"R113","name":"Lubuk Gaung Refinery","group":"Lubuk Gaung Refinery"}},
                       "historical_pcf_per_unit": 2.20},
        },
    },
    {
        "id": "BUYER_UNILEVER", "name": "Unilever",
        "country": "United Kingdom", "segment": "Consumer Goods / FMCG",
        "max_pcf_limit": 2.0, "discharge_port": "Rotterdam, Netherlands",
        "products": {
            "RBDPO": {"label":"RBD Palm Olein","historical_quantity_mt": 75000.0,
                      "historical_route":{"estate":{"id":"2020","name":"Naga Mas Estate","spec":"EUDR"},
                                          "mill":  {"id":"2050","name":"Naga Sakti Mill","spec":"EUDR"},
                                          "refinery":{"id":"RJKT","name":"Marunda Refinery","group":"Marunda Refinery"}},
                      "historical_pcf_per_unit": 1.95},
            "CPO":   {"label":"Crude Palm Oil","historical_quantity_mt": 75000.0,
                      "historical_route":{"estate":{"id":"2320","name":"Indrasakti Estate","spec":"EUDR"},
                                          "mill":  {"id":"2350","name":"Indrasakti Mill","spec":"EUDR"},
                                          "refinery":{"id":"T115","name":"Belawan Refinery","group":"Belawan Refinery"}},
                      "historical_pcf_per_unit": 1.78},
            "PFAD":  {"label":"Palm Fatty Acid Distillate","historical_quantity_mt": 75000.0,
                      "historical_route":{"estate":{"id":"1020","name":"Padang Halaban Estate","spec":"EUDR"},
                                          "mill":  {"id":"1050","name":"Padang Halaban Mill","spec":"EUDR"},
                                          "refinery":{"id":"T126","name":"Surabaya Refinery","group":"Surabaya Refinery"}},
                      "historical_pcf_per_unit": 2.05},
        },
    },
    {
        "id": "BUYER_CARGILL", "name": "Cargill",
        "country": "United States", "segment": "Commodity Trading",
        "max_pcf_limit": 2.8, "discharge_port": "New Orleans, USA",
        "products": {
            "CPO":   {"label":"Crude Palm Oil","historical_quantity_mt": 75000.0,
                      "historical_route":{"estate":{"id":"1922","name":"Nenggala Estate","spec":"EUDR"},
                                          "mill":  {"id":"1950","name":"Libo Mill","spec":"EUDR"},
                                          "refinery":{"id":"T130","name":"Tarjun Refinery","group":"Tarjun Refinery"}},
                      "historical_pcf_per_unit": 2.20},
            "PKO":   {"label":"Palm Kernel Oil","historical_quantity_mt": 75000.0,
                      "historical_route":{"estate":{"id":"2521","name":"Sungai Merah Estate","spec":"EUDR"},
                                          "mill":  {"id":"2551","name":"Sungai Merah Mill","spec":"EUDR"},
                                          "refinery":{"id":"R113","name":"Lubuk Gaung Refinery","group":"Lubuk Gaung Refinery"}},
                      "historical_pcf_per_unit": 1.65},
            "RBDPO": {"label":"RBD Palm Olein","historical_quantity_mt": 75000.0,
                      "historical_route":{"estate":{"id":"3226","name":"Perdana Estate","spec":"EUDR"},
                                          "mill":  {"id":"3251","name":"Perdana Mill","spec":"EUDR"},
                                          "refinery":{"id":"T130","name":"Tarjun Refinery","group":"Tarjun Refinery"}},
                      "historical_pcf_per_unit": 2.10},
        },
    },
    {
        "id": "BUYER_AAK", "name": "AAK",
        "country": "Sweden", "segment": "Specialty Fats",
        "max_pcf_limit": 1.8, "discharge_port": "Malmö, Sweden",
        "products": {
            "RBDPO":  {"label":"RBD Palm Olein","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3226","name":"Perdana Estate","spec":"EUDR"},
                                           "mill":  {"id":"3251","name":"Perdana Mill","spec":"EUDR"},
                                           "refinery":{"id":"T115","name":"Belawan Refinery","group":"Belawan Refinery"}},
                       "historical_pcf_per_unit": 1.72},
            "RBDPKO": {"label":"RBD Palm Kernel Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3228","name":"Muara Dua Estate","spec":"EUDR"},
                                           "mill":  {"id":"3253","name":"Sungai Rungau Mill","spec":"EUDR"},
                                           "refinery":{"id":"T115","name":"Belawan Refinery","group":"Belawan Refinery"}},
                       "historical_pcf_per_unit": 1.91},
            "RBDOLN": {"label":"RBD Palm Olein (Low IV)","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3229","name":"Lenggana Estate","spec":"EUDR"},
                                           "mill":  {"id":"3253","name":"Sungai Rungau Mill","spec":"EUDR"},
                                           "refinery":{"id":"T115","name":"Belawan Refinery","group":"Belawan Refinery"}},
                       "historical_pcf_per_unit": 1.88},
        },
    },
    {
        "id": "BUYER_PG", "name": "Procter & Gamble",
        "country": "United States", "segment": "Consumer Goods / Personal Care",
        "max_pcf_limit": 2.1, "discharge_port": "Houston, USA",
        "products": {
            "RBDPO":  {"label":"RBD Palm Olein","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"1423","name":"Tanjung Paring Estate","spec":"EUDR"},
                                           "mill":  {"id":"1451","name":"Hanau Mill","spec":"EUDR"},
                                           "refinery":{"id":"T130","name":"Tarjun Refinery","group":"Tarjun Refinery"}},
                       "historical_pcf_per_unit": 1.98},
            "CPO":    {"label":"Crude Palm Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"1424","name":"Tasik Mas Estate","spec":"EUDR"},
                                           "mill":  {"id":"1456","name":"Semilar Mill","spec":"EUDR"},
                                           "refinery":{"id":"T130","name":"Tarjun Refinery","group":"Tarjun Refinery"}},
                       "historical_pcf_per_unit": 1.84},
            "RBDOLN": {"label":"RBD Palm Olein (Low IV)","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"1425","name":"Medang Sari Estate","spec":"EUDR"},
                                           "mill":  {"id":"1451","name":"Hanau Mill","spec":"EUDR"},
                                           "refinery":{"id":"T130","name":"Tarjun Refinery","group":"Tarjun Refinery"}},
                       "historical_pcf_per_unit": 2.05},
        },
    },
    {
        "id": "BUYER_BASF", "name": "BASF",
        "country": "Germany", "segment": "Oleochemicals / Specialty Chemicals",
        "max_pcf_limit": 2.6, "discharge_port": "Hamburg, Germany",
        "products": {
            "CPO":    {"label":"Crude Palm Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"2121","name":"Rama Bhakti Estate","spec":"EUDR"},
                                           "mill":  {"id":"2050","name":"Naga Sakti Mill","spec":"EUDR"},
                                           "refinery":{"id":"T114","name":"Lampung Refinery","group":"Lampung Refinery"}},
                       "historical_pcf_per_unit": 2.30},
            "PKO":    {"label":"Palm Kernel Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"1922","name":"Nenggala Estate","spec":"EUDR"},
                                           "mill":  {"id":"1950","name":"Libo Mill","spec":"EUDR"},
                                           "refinery":{"id":"T114","name":"Lampung Refinery","group":"Lampung Refinery"}},
                       "historical_pcf_per_unit": 1.60},
            "RBDPKO": {"label":"RBD Palm Kernel Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"1923","name":"Palapa Estate","spec":"EUDR"},
                                           "mill":  {"id":"1951","name":"Samsam Mill","spec":"EUDR"},
                                           "refinery":{"id":"T114","name":"Lampung Refinery","group":"Lampung Refinery"}},
                       "historical_pcf_per_unit": 1.75},
        },
    },
    {
        "id": "BUYER_WILMAR", "name": "Wilmar International",
        "country": "Singapore", "segment": "Agribusiness / Palm Processing",
        "max_pcf_limit": 3.0, "discharge_port": "Singapore",
        "products": {
            "CPO":    {"label":"Crude Palm Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3820","name":"Sulin Estate","spec":"EUDR"},
                                           "mill":  {"id":"5150","name":"Sako Mill","spec":"EUDR"},
                                           "refinery":{"id":"R113","name":"Lubuk Gaung Refinery","group":"Lubuk Gaung Refinery"}},
                       "historical_pcf_per_unit": 2.55},
            "RBDPO":  {"label":"RBD Palm Olein","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3821","name":"Katayang Estate","spec":"EUDR"},
                                           "mill":  {"id":"4450","name":"Kuayan Mill","spec":"EUDR"},
                                           "refinery":{"id":"RJKT","name":"Marunda Refinery","group":"Marunda Refinery"}},
                       "historical_pcf_per_unit": 2.78},
            "RBDOLN": {"label":"RBD Palm Olein (Low IV)","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3822","name":"Nahiyang Estate","spec":"EUDR"},
                                           "mill":  {"id":"4450","name":"Kuayan Mill","spec":"EUDR"},
                                           "refinery":{"id":"RJKT","name":"Marunda Refinery","group":"Marunda Refinery"}},
                       "historical_pcf_per_unit": 2.90},
        },
    },
    {
        "id": "BUYER_RECKITT", "name": "Reckitt Benckiser",
        "country": "United Kingdom", "segment": "Personal Care / Hygiene",
        "max_pcf_limit": 2.3, "discharge_port": "Liverpool, UK",
        "products": {
            "CPO":    {"label":"Crude Palm Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3229","name":"Lenggana Estate","spec":"EUDR"},
                                           "mill":  {"id":"3253","name":"Sungai Rungau Mill","spec":"EUDR"},
                                           "refinery":{"id":"T126","name":"Surabaya Refinery","group":"Surabaya Refinery"}},
                       "historical_pcf_per_unit": 2.05},
            "RBDPO":  {"label":"RBD Palm Olein","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3822","name":"Nahiyang Estate","spec":"EUDR"},
                                           "mill":  {"id":"3850","name":"Tangar Mill","spec":"EUDR"},
                                           "refinery":{"id":"T126","name":"Surabaya Refinery","group":"Surabaya Refinery"}},
                       "historical_pcf_per_unit": 2.18},
            "RBDPKO": {"label":"RBD Palm Kernel Oil","historical_quantity_mt": 75000.0,
                       "historical_route":{"estate":{"id":"3227","name":"Semandau Estate","spec":"EUDR"},
                                           "mill":  {"id":"3850","name":"Tangar Mill","spec":"EUDR"},
                                           "refinery":{"id":"T126","name":"Surabaya Refinery","group":"Surabaya Refinery"}},
                       "historical_pcf_per_unit": 1.95},
        },
    },
]

_BUYER_INDEX: Dict[str, Dict[str, Any]] = {b["id"]: b for b in BUYER_CATALOGUE}

REFINERY_CURRENT_CAPACITY: Dict[str, float] = {
    "Lubuk Gaung Refinery": 38_500.0,
    "Lampung Refinery":     44_200.0,
    "Marunda Refinery":     41_000.0,
    "Belawan Refinery":     33_800.0,
    "Tarjun Refinery":      36_000.0,
    "Surabaya Refinery":    51_000.0,
}

_ROUTE_KM: Dict[str, Dict[str, float]] = {
    "R113": {"em": 80.0, "mr": 350.0},
    "T114": {"em": 55.0, "mr": 220.0},
    "RJKT": {"em": 90.0, "mr": 480.0},
    "T115": {"em": 65.0, "mr": 290.0},
    "T130": {"em": 75.0, "mr": 310.0},
    "T126": {"em": 95.0, "mr": 420.0},
}
